---
title: "Tidyverse"
author: "Omar Hegazy"
Matriculation number: "568463"
---

# Challenge: 
## Analyze the sales by location (state) with a bar plot.


```{r}
# libraries
library(tidyverse)
library(readxl)
library(lubridate)
library("writexl")
# Importing Files 
bikes_tbl      <- read_excel(path = "Data_bikes/01_bike_sales/01_raw_data/bikes.xlsx")
orderlines_tbl <- read_excel("Data_bikes/01_bike_sales/01_raw_data/orderlines.xlsx")
bikeshops_tbl  <- read_excel("Data_bikes/01_bike_sales/01_raw_data/bikeshops.xlsx")

# Examining Data
#orderlines_tbl
#glimpse(orderlines_tbl)

# Linking Data
bike_orderlines_joined_tbl <- orderlines_tbl %>% 
  left_join(bikes_tbl, by =c("product.id"="bike.id")) %>%
  left_join(bikeshops_tbl, by =c("customer.id"="bikeshop.id"))


# Wrangling Data 

bike_state_wrangled_tbl <- bike_orderlines_joined_tbl%>%
  separate(col=location,
           into= c("city","state"),
           sep= ",")%>%
mutate(total.price= price * quantity)%>%
select(-...1, -gender)%>%
 select(order.id,city,state,order.date, total.price, contains("model"), contains("category"),
         price, quantity,
         everything()) %>%
  rename(bikeshop = name) %>%
  set_names(names(.) %>% str_replace_all("\\.", "_"))

  

# Business Insights 
# Sales by Location 

#1 Manipulating

state_sales <- bike_state_wrangled_tbl%>%
  select(state,total_price)%>%
  group_by(state)%>%
  summarize(sales=sum(total_price))%>%
  mutate(sales_text = scales::dollar(sales, big.mark = ".", 
                                     decimal.mark = ",", 
                                     prefix = "", 
                                     suffix = " €"))
#2 Visualizing
state_sales %>%
  
  # columns year (x-axis) and sales (y-axis)
  ggplot(aes(x = state, y = sales)) +
  
  # Geometry
  geom_col(fill = "#3b965c") + # bar plot
  geom_label(aes(label = sales_text)) + # labels
  geom_smooth(method = "lm", se = FALSE) + # trendline
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  + 
  # Format
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", 
                                                    decimal.mark = ",", 
                                                    prefix = "", 
                                                    suffix = " €")) +
  labs(
    title    = "Revenue by States",
    x = "State(province)", # Override defaults for x and y
    y = "Revenue"
  )
```


### Which state has the highest revenue?

 **"North Rhine-Westphalia"** has the highest revenue according to the bar-chart shown above.

# Challenge

## Analyze the sales by location and year. 


```{r}
#Sales(Location and Year)

#1 Manipulating
sales_by_location_year <- bike_state_wrangled_tbl %>%
  
  # Select columns and add a year
  select(order_date, total_price,state) %>%
  mutate(year = year(order_date)) %>%
  
  # Group by and summarize year and state
  group_by(year,state) %>%
  summarise(sales = sum(total_price)) %>%
  ungroup() %>%
  
  # Format $ Text
  mutate(sales_text = scales::dollar(sales, big.mark = ".", 
                                     decimal.mark = ",", 
                                     prefix = "", 
                                     suffix = " €"))

#2 Visualizing
sales_by_location_year %>%
  
  # Set up the axis then fill
  ggplot(aes(x = year, y = sales, fill = state)) +
  
  # Geometry
  geom_col() + # Run up to here to get a stacked bar plot
  
  # Facet wrap analyzing
  facet_wrap(~ state) +
  
  # Format
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", 
                                                    decimal.mark = ",", 
                                                    prefix = "", 
                                                    suffix = " €")) +
  labs(
    title = "Revenue by year and State",
    fill = "States categories" 
  )
```

